name: Scheduled CI Workflow

on:
  schedule:
    - cron: '15 16 * * *'  # Runs daily at 4:15 PM UTC (which corresponds to 9:45 PM IST)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main  # Ensures the checkout is from the main branch

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests with marker
      run: |
        pytest -m "basic_flows" --alluredir=allure-results  # Run tests with the 'basic_flows' marker

    - name: Generate Allure report
      run: |
        allure serve allure-results  # Serve the Allure report locally
