name: Scheduled CI Workflow

on:
  schedule:
    - cron: '10 18 * * *'  # Runs daily at 6:10 PM GMT (which is 11:40 PM IST)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main  # Ensure checking out the 'main' branch

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests with marker
      run: |
        pytest -m "basic_flows"
