name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Remove GitHub extraheader
      run: |
        set -x
        if git config --global --get http.https://github.com/.extraheader; then
          git config --global --unset-all http.https://github.com/.extraheader
        fi
        git submodule foreach --recursive 'if git config --local --get http.https://github.com/.extraheader; then git config --local --unset-all http.https://github.com/.extraheader; fi || true'
        set +x

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests with marker
      run: |
        pytest -m "basic_flows"

    - name: Generate Allure report
      run: |
        allure serve allure-results

